// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuOAKi6AjbZuzKwsF3yZB7At4gZldRgYc',
    appId: '1:496644722777:web:36c5be9c52512890422148',
    messagingSenderId: '496644722777',
    projectId: 'pesanbuku-8c0a5',
    authDomain: 'pesanbuku-8c0a5.firebaseapp.com',
    storageBucket: 'pesanbuku-8c0a5.firebasestorage.app',
    measurementId: 'G-6JPHJHL9E6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwgawB0Vf-5xV5_H7wvljKgiWzgRvxT4M',
    appId: '1:496644722777:android:bf6d45c81f8f81d3422148',
    messagingSenderId: '496644722777',
    projectId: 'pesanbuku-8c0a5',
    storageBucket: 'pesanbuku-8c0a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLPQklO7cgjVret5bekY0W8sC2IfSZFgk',
    appId: '1:496644722777:ios:a157d8f72b1ccfce422148',
    messagingSenderId: '496644722777',
    projectId: 'pesanbuku-8c0a5',
    storageBucket: 'pesanbuku-8c0a5.firebasestorage.app',
    iosBundleId: 'com.example.pesanbukuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLPQklO7cgjVret5bekY0W8sC2IfSZFgk',
    appId: '1:496644722777:ios:a157d8f72b1ccfce422148',
    messagingSenderId: '496644722777',
    projectId: 'pesanbuku-8c0a5',
    storageBucket: 'pesanbuku-8c0a5.firebasestorage.app',
    iosBundleId: 'com.example.pesanbukuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuOAKi6AjbZuzKwsF3yZB7At4gZldRgYc',
    appId: '1:496644722777:web:74fdef4afd9f93a7422148',
    messagingSenderId: '496644722777',
    projectId: 'pesanbuku-8c0a5',
    authDomain: 'pesanbuku-8c0a5.firebaseapp.com',
    storageBucket: 'pesanbuku-8c0a5.firebasestorage.app',
    measurementId: 'G-ZYHDJRBPTZ',
  );
}
